src/e_ibmca.c
Setting as NULL the rsa_keygen field of RSA_METHOD structure when using
openssl < 1.1.0. Setting as NULL, the builtin RSA key generation will
be used.
This patch fixes GitHub issue #2
=> Initialize rsa_keygen in RSA_METHOD for openssl < 1.1.0

src/e_ibmca.c
When running system in FIPS mode (libica >=3.0.0 can be configured with
the --enable-fips option to have built-in FIPS 140-2), the
OpenSSL/ibmca/libica stack crashes (SIGSEGV) in OpenSSL's RNG (which
uses SHA-1).
This patch enables the EVP_MD_FLAG_FIPS flag for SHA1, SHA256, SHA512
EVP_MD structure.
This fixes the GitHub issue #4
=> Enable EVP_MD_FLAG_FIPS flag for SHA-*.

src/e_ibmca.c
The engine initialization, ibmca_init() function, can be called more than
once causing the code to jump to a exit label where all internal function
pointers are set to NULL, which can cause a SIGSEGV.
This patch guarantees that the internal pointers will be set only once, by
exiting the ibmca_init() if already executed.
This patch fixes Ubuntu's LP#1443455
Signed-off-by: Harald Freudenberger <freude@linux.vnet.ibm.com>
=> Fix engine initialization to set funtion pointers only once.

src/e_ibmca.c
Add AES-GCM support to ibmca.
Code builts with  with OpenSSL versions < and >= 1.1.0. Test suite's AES-GCM test vectors pass, but the patches still needs a carefull review, because all the messy ifdefs ... Do we have test cases for the engine ?
=> Add AES-GCM support.

configure.ac
Setting 'foreign' strictness for automake stops silly things like
'not having a NEWS file' being a fatal error.
https://www.gnu.org/software/automake/manual/html_node/Strictness.html
Fixes #13
=> Setting 'foreign' strictness for automake.

src/e_ibmca.c
ibmca did not built with openssl 1.0.1e-fips on rhel 7.3. reintroduce the missing define.
=> Add compat macro for OpenSSL 1.0.1e-fips.

configure.ac
Removed AC_FUNC_MALLOC from configure.ac, to make sure we are using
malloc() instead of rpl_malloc().
For more information search for AC_FUNC_MALLOC in
https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/Particular-Functions.html
Fixes #12
Siggned-off-by: Paulo Vital <pvital@linux.vnet.ibm.com>
=> Remove AC_FUNC_MALLOC from configure.ac

LICENSE, bootstrap.sh, cleanup.sh, openssl-ibmca.spec, src/e_ibmca.c, src/e_ibmca_err.c, src/e_ibmca_err.h, src/test/ibmca_mechaList_test.c
Moving to Apache License v2.0 following the OpenSSL process to
re-license the project. For more information, see [1].
[1] https://www.openssl.org/blog/blog/2017/03/22/license/
=> Re-license to Apache License v2.0

openssl-ibmca.spec
Make installation to /usr/share/doc/ibmca work again:
README -> README.md, remove INSTALL.
=> Update spec file.

src/e_ibmca.c
Structures were the same size as for aes-gcm. Didnt cause any
problems because aes-gcm structure is the biggest.
=> fix structure size for aes-256-ecb/cbc/cfb/ofb

src/Makefile.am, src/openssl.cnf.sample
When the filename and engine name are the same (omitting the .so suffix), then it's possible to use the engine without configuration in openssl.conf (eg. "openssl speed -engine ibmca" works).
=> switch to ibmca.so filename to allow a standalone use

src/Makefile.am
Back in commit 5061482 we removed some old OpenSSL header files that
were not needed anymore. Ended up forgetting to update the Makefile.
Signed-off-by: Eduardo Barretto <ebarretto@linux.vnet.ibm.com>
=> Update Makefile as some header files were removed

README.md, configure.ac, openssl-ibmca.spec, src/doc/ibmca.man, src/openssl.cnf.sample, src/test/ibmca_mechaList_test.c
Updating documentation, spec file and test code to the new lib name.
Also switching m4s macro that was deprecated to newest one.
=> Update m4s macro, documentation, spec file and test code

src/e_ibmca.c
- Make Ibmca use the fallback API at Libica if available to switch off the fallbacks.
- Ibmca init function was called twice because of race condition at the local static init variable.
- Provide DEBUG_PRINTF macro for very simple and easy debugging possibility.
=> Minor code changes and improvements.

src/e_ibmca.c
=> Replace compile-time openssl version checking by compat macros

src/e_ibmca.c
dlclose returns 0 on success and the current code was treating success
as an error.
This fixes #37.
Signed-off-by: Eduardo Barretto <ebarretto@linux.vnet.ibm.com>
=> Fix dlclose logic

src/e_ibmca.c
We cant disable libica sw fallbacks at this time for they are still
needed to handle > 4k rsa.
=> Dont disable libica sw fallbacks

src/Makefile.am
The ibmca.so file is a dlopen()-ed module, so having the version info
in the filename is superfluous.
=> omit version from filename

src/ibmca_rsa.c
rsa-crt is preferred to rsa-me when possible for performance reason.
This bug was introduced with commit dc8465b (ibmca >= 1.3.1) for
openssl >= 1.1.0. Commit ed496f6 (ibmca >= 2.0.0) introduced the bug
also for openssl versions < 1.1.0.
=> Fix doing rsa-me, altough rsa-crt would be possible

src/e_ibmca.c, src/ibmca_cipher.c, src/ibmca_dh.c, src/ibmca_dsa.c, src/ibmca_rsa.c
Enable engine to be used with openssl fips builds.
=> Set *_FLAG_FIPS_METHOD flags

README.md
README's instructions on how to configure the engine via editing
openssl.cnf do not work for all possible configurations.
Remove those misleading instructions add a reference to OpenSSL's
documentation instead.
=> Remove misleading instructions from README

src/ibmca_cipher.c
ibmca_aes_gcm is expected to return 0 on failure and 1 on success (like most openssl functions). However, in case the length check fails -1 was returned, indicating success.
=> Fix length check for maximum length of aes-gcm payload

test/eckey.c
Without crypto cards on a machine < z14, ibmca might not register with the
EC_KEY subsystem of OpenSSL.  In these cases, the eckey test should be skipped
since it is doomed to fail.
Fixes #69.
=> Skip eckey test if needed.

src/ibmca_dh.c, src/ibmca_dsa.c
DSA does not provide backups by default.
Also fix typo in DH initialization.
=> Fix DSA and DH registration.

src/ibmca_pkey.c, src/openssl-compat.h
ED25519, ED448, X25519, and X448 caused a segmentation fault due to wrong
usage of ECX keys.
=> PKEY: Fix usage of ECX keys

.gitignore, configure.ac, src/test/Makefile.linux.in
Generate the Makefile for ibmca_mechaList_test during the configure run,
so it links with the same libica variant as used by the ibmca.so module.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2059489
=> use correct libica for ibmca_mechaList_test

test/provider/Makefile.am
The RSA 16K test alone runs for about 30 minutes. Since the RSA 8K test already utilizes the fall-backs, testing RSA 16K does not add much of test coverage.
=> test/provider: Don't run RSA 16K test to reduce the test run time

src/engine/openssl-compat.h
ECX_KEY structure as used by engine is not public API in OpenSSL 3.0 and
should not be included via a private header.  This forced the engine to only
compile if the OpenSSL 3.0 source tree is present.  While this might be the
cleaner solution, we now copy out the defines to be used.  This makes the
engine compile even without OpenSSL 3.0 source tree.
=> Fix compilation for OpenSSL 3.0

src/provider/dh_keymgmt.c, src/provider/ec_keymgmt.c, src/provider/rsa_keymgmt.c
OpenSSL commit [ee22a3741e3fc27c981e7f7e9bcb8d3342b0c65a ](https://github.com/openssl/openssl/commit/ee22a3741e3fc27c981e7f7e9bcb8d3342b0c65a) changed the OpenSSL provider's keymgmt_match() function to be not so strict with the selector bits in regards to matching different key parts.
Adapt the provider's match functions accordingly.
This means, that if the public key is selected to be matched, and the public key matches (together with any also selected parameters), then the private key is no longer checked, although it may also be selected to be matched. This is according to how the OpenSSL function EVP_PKEY_eq() is supposed to behave.
Signed-off-by: Ingo Franzki <ifranzki@linux.ibm.com>
=> provider: Adapt keymgmt_match() implementations to OpenSSL

test/provider/Makefile.am, test/provider/dhkey.c, test/provider/eckey.c, test/provider/rsakey.c
Before actually running the tests, check if libica supports the required algorithms. Skip the whole test if not.
This can happen when running the test on a system without appropriate crypto adapters. This would lead to the situation that the provider would not register itself for the required algorithms, and thus the OpenSSL default provider would be used. This would make the tests to fail, because it is not running with the IBMCA provider as expected by the test.
Fixes https://github.com/opencryptoki/openssl-ibmca/issues/84
=> tests: skip tests if libica does not support required algorithms

test/provider/test.pm
Make key file names unique and do not use killall.
=> Provider: Fix parallel test runs

src/provider/ec_keymgmt.c, src/provider/p_ibmca.h
In general the IBMCA provider does not support EC parameter generation, because libica only supports certain named curves. However, one can also use EC parameter generation with a named curve, and then use such parameter key object as template for generating other keys. One example for this is the openssl speed utility.
Like for EC key generation, EC parameter generation only supports parameters 'group', 'point-format', 'encoding', and 'use-cofactor-flag', where the only accepted value for parameter 'encoding' is 'named_curve', and the only accepted value for parameter 'use-cofactor-flag' is '0'.
With this change the openssl speed utility works fine with ECDSA.
=> provider: Support EC parameter generation with named curve

src/engine/e_ibmca.c, src/engine/ibmca.h, src/engine/ibmca_ec.c
Creating a new ICA EC key via ica_ec_key_init() is time consuming, because libica performs EC key checks on the key components.
Currently every sign, verify or derive operation creates a new ICA key, and thus suffers from the long taking EC key checks with every operation.
Change this to create an ICA key on the first usage of an EC key, and attach the ICA key to the EC_KEY object as ex-data. That way, subsequent operations using the same key will reuse the attached ICA key and do not have to create a new ICA key again.
=> engine: EC: Cache ICA key in EC_KEY object

src/provider/ibmca-provider-opensslconfig
Small typo in the configuration script created an invalid configuration.
=> [Provider] Fix configuration script

src/provider/dh_keymgmt.c, src/provider/ec_keymgmt.c, src/provider/ec_signature.c, src/provider/rsa_asym_cipher.c, src/provider/rsa_keymgmt.c, src/provider/rsa_signature.c
Update the IBMCA provider code to know newly added parameters and changed behavior that were added to the OpenSSL code base over time. 
Note that most code changes in this PR are only included when compiling against a newer OpenSSL library, i.e. >= OpenSSL 3.1. For compiled against OpenSSL 3.0 the changes should be a no-change.
=> Provider currency

src/provider/ec_signature.c
OpenSSL now also allows to retrieve parameter OSSL_SIGNATURE_PARAM_NONCE_TYPE, so the IBMCA provider should allow that, too. Always return 0 to indicate that we do not support deterministic signatures.
Related OpenSSL commit: https://github.com/openssl/openssl/commit/1d857945324810f43a302c9d062c617207093387
=> provider: EC signature: Allow OSSL_SIGNATURE_PARAM_NONCE_TYPE to be retrieved

src/engine/ibmca_rsa.c
For whatever reason RSA blinding was disabled for the IBMCA engine. One possible reason is that setting up the blinding factors also requires a mod-expo operation, and this operation does not get offloaded to libica, unless a Montgomery context for the public key (modulus) was setup before.
Do no longer disable blinding, but make sure that a Montgomery contexts for the public and private keys are cached, like it is done without an engine. That way the mod-expo operation used for setting up the blinding context is also offloaded via ibmca_mod_exp().
Note: Due to a bug in OpenSSL code, the offloading of the mod-expo for the blinding setup does currently not work for private decrypt operations, but only for private encrypt (signature create) operations. Once that bug is fixed in OpenSSL, it …
=> engine: Enable RSA blinding and offload blinding setup to libica

src/engine/doc/ibmca.man, src/engine/ibmca-engine-opensslconfig.in, src/engine/openssl.cnf.sample, src/provider/doc/ibmca-provider.man, src/provider/ibmca-provider-opensslconfig, src/provider/openssl.cnf.provider.sample
- Add notes about not trying to accelerating algorithms that are already accelerated by OpenSSL itself using CPACF.
- Also add a note about disabling FIPS mode for the IBMCA provider because the provider is not FIPS certified.
- Fix the provider config file generator to generate the default name for the evp_properties section.
=> Doc and example config file updates

src/engine/e_ibmca.c
As part of OpenSSl initialization, the engine(s) configured in the OpenSSL config file are loaded, and its algorithms (methods) are registered according to the default_algorithms setting.
However, later during initialization, ENGINE_register_all_complete() is called which unconditionally registered all algorithms (methods) of the loaded engines again, unless the engine flag ENGINE_FLAGS_NO_REGISTER_ALL is set.
Set the ENGINE_FLAGS_NO_REGISTER_ALL flag during IBMCA engine initialization to avoid unconditional registration of all algorithms. We only want to register thise algorithms specified in the default_algorithms configuration setting.
Note that if the default_algorithms setting is omitted in the OpenSSL config file, then no algorithms will be registered.
=> engine: Only register those algos specified with default_algorithms

src/provider/p_ibmca.h, src/provider/rsa_asym_cipher.c, src/provider/rsa_blinding.c, src/provider/rsa_keymgmt.c, src/provider/rsa_signature.c
RSA private keys may contain just CRT (p, q, dp, dq, qinv) or ME (d) components, or all of them. If an application imports a private RSA key from just the ME components (m, e, and private d), then the IBMCA provider can not use ica_rsa_crt() to perform private key operations.
Therefore let an RSA key also contain the private key components in ME format, and use ica_rsa_mod_expo() if only the ME components are available. RSA keys are still always generated in CRT format, but it now allows to import an RSA private key in ME format.
=> provider: Support importing of RSA keys with just ME components

configure.ac, src/provider/Makefile.am, src/provider/doc/ibmca-provider.man, src/provider/p_ibmca.c, src/provider/p_ibmca.h, test/provider/openssl-test.cnf
The IBMCA provider debug logs were written to the /var/log/ibmca/ directory, but this required that directory to be world-writable, because we don't know under which user an application runs that uses the provider. A world-writable directory under /var has security implications and should be avoided.
Change the default log directory to /tmp which is world-writable anyway. Additionally the log directory can now be configured via the 'debug-path' option in the IBMCA provider section of the OpenSSL config file, or via environment variable 'IBMCA_DEBUG_PATH'.
Closes: https://github.com/opencryptoki/openssl-ibmca/issues/107
=> provider: Default debug directory to /tmp but make it configurable

src/engine/e_ibmca.c, src/engine/ibmca.h
When the system is in FIPS mode, newer libica versions may prevent AES-GCM from being used with an external IV. FIPS requires that the AES-GCM IV is created libica internally via an approved random source.
The IBMCA engine can not support the internal generation of the AES-GCM IV, because the engine API for AES-GCM does not allow this. Applications using OpenSSL to perform AES-GCM (e.g. the TLS protocol) may require to provide an external IV.
Enable the use of external AES-GCM IVs for libica, if the used libica library supports this. Newer libica versions support to allow external AES-GCM IVs via function ica_allow_external_gcm_iv_in_fips_mode().
=> engine: Enable external AES-GCM IV when libica is in FIPS mode

configure.ac, test/provider/Makefile.am, test/provider/dhkey.c, test/provider/eckey.c, test/provider/rsakey.c
When an application links against libica (via -lica), then the libica library constructor runs before the program's main function. Libica's library constructor does initialize OpenSSL and thus parses the config file.
However, the test programs set up some OpenSSL configuration related environment variables within function check_libica() called from the the main function. If libica has already initialized OpenSSL prior to that, OpenSSL won't initialize again, and thus these environment variables have no effect.
Dynamically load libica (via dlopen) only after setting the environment variables.
=> test/provider: Do not link against libica use dlopen instead

test/provider/dhkey.c, test/provider/eckey.c, test/provider/rsakey.c
When running with a libica version without commit https://github.com/opencryptoki/libica/commit/42e197f61b298c6e6992b080c1923e7e85edea5a it is necessary to explicitly initialize OpenSSL before loading libica. Because otherwise libica's library constructor will initialize OpenSSL the first time, which in turn will load the IBMCA provider, and it will fall into the same problem as fixed by above libica commit, i.e. the provider won't be able to get the supported algorithms from libica an thus will not register any algorithms.
=> test/provider: Explicitly initialize OpenSSL after setting env vars

src/engine/ibmca_pkey.c
```
ibmca_pkey.c:627:47: error: passing argument 2 of 'EVP_PKEY_meth_set_copy' from incompatible pointer type [-Wincompatible-pointer-types]
627 |     EVP_PKEY_meth_set_copy(ibmca_ed448_pmeth, ibmca_ed448_copy);
```
=> engine: Fix compile error on Fedora 40

src/provider/dh_keymgmt.c, src/provider/rsa_keymgmt.c
Command 'openssl list -key-managers -verbose' calls OpenSSL function EVP_KEYMGMT_gen_settable_params() which in turn calls the provider's gen_settable_params() function, but with NULL for the keygen operation context. This causes segfaults in IBMCAs gen_settable_params() functions, as they assume that the keygen operation context is not NULL.
=> provider: Fix segfault with 'openssl list -key-managers -verbose'

src/provider/ec_signature.c, src/provider/p_context.c, src/provider/rsa_signature.c
Command 'openssl list -signature-algorithms -verbose' calls OpenSSL function EVP_SIGNATURE_settable_ctx_params() which in turn calls the provider's settable_ctx_params() function, but with NULL for the operation context. This causes segfaults in IBMCAs settable_ctx_params() functions, as they assume that the operation context is not NULL.
While at it, make sure that the settable/gettable_ctx_md_params() functions do not crash if called with a NULL context.
=> provider: Fix segfault with 'openssl list -signature-algorithms -verbose'

src/engine/ibmca_ec.c
In case EC key creation using libica fails (for whatever reason), and the software fallback is used to perform the operation, do not report the errors that have been put to the error stack by the failing attempt to use libica.
Fixes: a462093d2478b287cb9a7a25131788eba16b7640
=> engine: Do not report errors if libica does not support EC key

src/engine/ibmca_ec.c
ibmca_ec.c:342:5: error: implicit declaration of function
'ERR_pop_to_mark' [-Wimplicit-function-declaration]
342 |     ERR_pop_to_mark();
|     ^~~~~~~~~~~~~~~
Fixes: 6bc53d814762b24045bfd5bb6003949a163fa58b
=> Fix compiler error for undefined ERR_pop_to_mark

configure.ac, src/provider/dh_keyexch.c, src/provider/ec_keyexch.c, src/provider/ec_keymgmt.c, src/provider/ec_signature.c, src/provider/p_context.c, src/provider/p_ibmca.c, src/provider/p_ibmca.h, src/provider/rsa_asym_cipher.c, src/provider/rsa_keymgmt.c, src/provider/rsa_signature.c, test/engine/enginectrl.c, test/engine/threadtest.c, test/provider/dhkey.c, test/provider/eckey.c, test/provider/rsakey.c, test/provider/threadtest.c
- Support deterministic EC signatures (nonzero OSSL_SIGNATURE_PARAM_NONCE_TYPE) via fallback provider.
- Support EC DHKEM (SSL_PKEY_PARAM_DHKEM_IKM) via fallback provider.
- Support SignMessage and VerifyMessage API (since OpenSSL 3.4) for ECDSA and RSA for composite hash-then-sign algorithms.
- Support import RSA keys from just P and Q (OSSL_PKEY_PARAM_RSA_DERIVE_FROM_PQ, since OpenSSL 3.3).
- Misc updates and fixes
Closes: https://github.com/opencryptoki/openssl-ibmca/issues/119
Closes: https://github.com/opencryptoki/openssl-ibmca/issues/114
=> Provider currency updates

configure.ac
Newer distributions do not install the include file `openssl/engine.h` anymore to actively hinder one from building and using engines.
Check if `openssl/engine.h` exists, and only enable the engine build if so. If the engine is explicitly enabled via '--enable-engine' then the configure step fails with an error message. Otherwise the engine is silently disabled.
=> configure: Check for openssl/engine.h and disable engine if not available
